apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: it-beyondit
    provider: github
    repository: prova
  name: it-beyondit-prova
spec:
  description: Imported application for it-beyondit/prova
  httpCloneURL: https://github.com/it-beyondit/prova.git
  org: it-beyondit
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: prova
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/it-beyondit/prova.git
