adminUser:
  password: local:kiko/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkinsx@beyondit.it
  token: local:kiko/pipelineUser:token
  username: JenkinsxBeyondIt
prow:
  hmacToken: local:kiko/prow:hmacToken
